image: maxking/mailman-ci-runner

stages:
  - test
  - quality-assurance

py36-django-2.0:
   stage: test
   script:
   - tox -e py36-django20

py36-django-2.1:
  stage: test
  script:
    - tox -e py36-django21

py36-django-2.2:
  stage: test
  script:
    - tox -e py36-django22

py37-django-2.1:
  stage: test
  script:
    - tox -e py37-django21

py37-django-2.2:
  stage: test
  script:
    - tox -e py37-django22

py36-django-3.0:
  stage: test
  script:
    - tox -e py36-django30

py37-django-3.0:
  stage: test
  script:
    - tox -e py37-django30

py38-django-2.2:
  stage: test
  script:
    - tox -e py38-django22

py39-django-2.2:
  stage: test
  script:
    - tox -e py39-django22

lint:
  stage: quality-assurance
  script:
  - tox -e lint

docs:
  stage: quality-assurance
  script:
  - tox -e docs

coverage:
  stage: quality-assurance
  script:
    - tox -e py38-django22-coverage

include:
  - template: SAST.gitlab-ci.yml

variables:
  SAST_DEFAULT_ANALYZERS: "bandit,secrets"


