---

image: ghcr.io/maxking/mailman-ci-runner:latest

stages:
  - test
  - quality-assurance

py36-django-2.2:
  stage: test
  script:
    - tox -e py36-django22

py36-django-3.0:
  stage: test
  script:
    - tox -e py36-django30

py36-django-3.1:
  stage: test
  script:
    - tox -e py36-django31

py37-django-2.2:
  stage: test
  script:
    - tox -e py37-django22

py37-django-3.0:
  stage: test
  script:
    - tox -e py37-django30

py38-django-2.2:
  stage: test
  script:
    - tox -e py38-django22

py38-django-3.0:
  stage: test
  script:
    - tox -e py38-django30

py38-django-3.1:
  stage: test
  script:
    - tox -e py38-django31

py39-django-2.2:
  stage: test
  script:
    - tox -e py39-django22

py39-django-3.0:
  stage: test
  script:
    - tox -e py39-django30

py39-django-3.1:
  stage: test
  script:
    - tox -e py39-django31

lint:
  stage: quality-assurance
  script:
    - tox -e lint

lint-js:
  image: node:latest
  stage: quality-assurance
  script:
    - npm install -g eslint
    - eslint -c .eslintrc.yml hyperkitty/static/hyperkitty/js

docs:
  stage: quality-assurance
  script:
    - tox -e docs

coverage:
  stage: quality-assurance
  script:
    - tox -e py38-django22-coverage

include:
  - template: SAST.gitlab-ci.yml

variables:
  SAST_DEFAULT_ANALYZERS: "bandit,secrets"
